plugins {
    id 'com.android.application'
}

android {
    namespace 'com.reversedrooms.pearlserver'
    compileSdk 34

    defaultConfig {
        applicationId 'com.reversedrooms.pearlserver'
        minSdk 26
        targetSdk 34

        versionCode 4554
        versionName '4.5.54'
    }

    // ============================================================
    // BuildConfig
    // ============================================================

    buildFeatures {
        buildConfig true
    }

    // ============================================================
    // Android Build Tools
    // ============================================================

    buildToolsVersion "34.0.0"

    // ============================================================
    // Native .so
    // ============================================================

    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
    }

    // ============================================================
    // Build Types
    // ============================================================

    buildTypes {

        release {
            // 不混淆
            minifyEnabled false

            // 不删除资源
            shrinkResources false

            // Native 库不启用 JNI 调试
            jniDebuggable false

            // ----------------------------------------------------
            // 注意：
            // 这里不要写 getDefaultProguardFile()
            // 因为当前 release 没有开启混淆。
            // ----------------------------------------------------
        }

        debug {
            jniDebuggable true
        }
    }

    // ============================================================
    // JNI Libs
    // ============================================================

    sourceSets {
        main {
            jniLibs.srcDirs = [
                    'src/main/jniLibs'
            ]
        }
    }

    // ============================================================
    // 保留 Native 调试符号
    // ============================================================

    packagingOptions {
        jniLibs {
            keepDebugSymbols += [
                    '**/libdispatch.so',
                    '**/libgameserver.so'
            ]
        }
    }
}

// ================================================================
// Dependencies
// ================================================================

dependencies {

    implementation 'androidx.core:core:1.13.1'
}
